### ISSUE TITLE
Implement a way to close Add Task Pop-Up

### ISSUE THREAD

**Issue by SauveJeanLuc** [SauveJeanLuc/coffee-tasks#1]
The current "Add Task Pop-Up" provides no way to close it.

![image](https://user-images.githubusercontent.com/68426990/192262969-dcc0309d-6af4-4188-9683-3956032fddca.png)

**Comment by aswinikalyan30** [comment]
Can I take this up?

**Comment by SauveJeanLuc** [comment]
> Can I take this up?

Yup, It's yours @aswinikalyan30

**Comment by SauveJeanLuc** [comment]
Hey, @aswinikalyan30 hope you are raising a PR for this today.
We are getting it merged tomorrow.

**Comment by Rudresh-pandey** [comment]
Hi, can i work on this?

**Comment by aswinikalyan30** [comment]
Hey, i thought this was part of hacktoberfest and was waiting for oct 1st

**Comment by SauveJeanLuc** [comment]
> Hey, i thought this was part of hacktoberfest and was waiting for oct 1st

Nop, u'll not have to wait for 1st October to raise a PR @aswinikalyan30 .
Hwvr, all PRs shall be merged from 1st October.

**Comment by SauveJeanLuc** [comment]
> Hi, can i work on this?

You can talk to @aswinikalyan30 and see on how to co-author this with her.

**Comment by aswinikalyan30** [comment]
@Rudresh-pandey you can go ahead and work on this. I felt it was only a bug, but this seems huge as there are a lot of fixes to be done, and I am short of time.

**Comment by SauveJeanLuc** [comment]
@aswinikalyan30 , you can still co-author this with @Rudresh-pandey .
There's always still a chance you know 🙂, and an opportunity to learn.

**Comment by SauveJeanLuc** [comment]
@Rudresh-pandey are you available for this?
Or we can assign it to another one in the mean time !?

**Comment by aadi58002** [comment]
Can i also take part in this pull request?

**Comment by SauveJeanLuc** [comment]
Yes @aadi58002 .
It's yours
