### ISSUE TITLE
Make a Mobile-Version Mock-Up for the Project on Figma

### ISSUE THREAD

**Issue by SauveJeanLuc** [SauveJeanLuc/coffee-tasks#10]
Project needs a mobile-version design on Figma.
 
 To get started, make a request for Edit Privileges on the
 [Figma Design](https://www.figma.com/file/2DdRHkoszU7lxTvcyBchJ8/React-TODO?node-id=0%3A1) And Thereafter, CREATE A PR/MR TO TRACK IT

**Comment by Rick-mad-lab** [comment]
Can I work on this part? 
I have already created some to-do templates before can you please assign this project to me?

**Comment by SauveJeanLuc** [comment]
Yup, Happy to have you joined 🎉
It's yours @Rick-mad-lab

**Comment by SauveJeanLuc** [comment]
@Rick-mad-lab  You can give me your username or ask for an edit request, so I can give you the Edit Privileges.

**Comment by Rick-mad-lab** [comment]
ok 
Sharanya Mitra
sharanyamitra28@gmail.com
this is my details 
give me editing privilege.

**Comment by SauveJeanLuc** [comment]
Done @Rick-mad-lab , you now have the edit privilege.

U'd take a look on #19  too, If you will.

**Comment by Vikramop** [comment]
Can I also try it cuz, I have also experience before in figma. 
veervikramsingh132@gmail.com
here's my mail if u wish I can start soon if u'll add me.

**Comment by SauveJeanLuc** [comment]
Glad to have you joined @Vikramop 🎉 .

Aniwei @Rick-mad-lab , @Vikramop  and any designer wanting to join.
You can join this server https://discord.gg/ZXBxStbA and join the designers channel.

**Comment by SauveJeanLuc** [comment]
We will have interesting brainstorming there 😎.
Make sure you tell me your username too 🙂

**Comment by hertafui** [comment]
Can I join this? And where I can see the site map to know the pages requirement to build,  could you tell me more about the projects please?

**Comment by pobrebobby** [comment]
I would love to keep learning. Could I help?

**Comment by SauveJeanLuc** [comment]
Yup, go for it @pobrebobby .

**Comment by SauveJeanLuc** [comment]
@hertafui warm welcome as well.
Take a reference on Discussions. You'll see some information there.
