### ISSUE TITLE
Edit tasks' status does not exist

### ISSUE THREAD

**Issue by duyenle1312** [SauveJeanLuc/coffee-tasks#103]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] This is bug in the application 🐛
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

**Describe the bug** \
After I created a new task, I cannot edit the task status to "Complete" or "Incomplete". The data is stored in local storage so I think I can create an easy way to edit the status using a pop up similar to create a new task and persist the change to local storage. 

**To Reproduce** \
1. Go to home page
2. Click on the task
3. Cannot edit the task

**Expected behavior** \
I expected to see the updated status on the home page.

**Current behaviour** \
Currently, the list is just read-only.

**Possible solutions** (Optional) \
Reuse the design of create a new task modal and allow users to edit status.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Failure Logs**

Please include any relevant log snippets or files here.

**Additional context**

**Comment by Drex72** [comment]
Can i be assigned to this @SauveJeanLuc

**Comment by SauveJeanLuc** [comment]
This awaits #85 to be complete.
