### ISSUE TITLE
Add a greeting card 

### ISSUE THREAD

**Issue by tanya172** [SauveJeanLuc/coffee-tasks#117]
Hello, there!
I would like to add a greeting card with animation to the webpage when the user is visiting the webpage. This will enhance the UI/UX experience of the user.

Kindly assign me the issue and add the Hacktober label. @SauveJeanLuc

**Comment by SauveJeanLuc** [comment]
@tanya172, can you show an example of how the greeting card shall look like ?

**Comment by tanya172** [comment]
A greeting card would wish the user according to the time . This feature
will add a good point and user engagement to the webpage

**Comment by SauveJeanLuc** [comment]
I mean, a visual representation of what it will look like
