### ISSUE TITLE
Add the initial TypeScript setup to begin using it in the repo

### ISSUE THREAD

**Issue by gaber85** [SauveJeanLuc/coffee-tasks#122]
I would love to work on implementing the initial Typescript setup so developers can start adding ts and tsx files.

Ideally, rather than using prop-types, TypeScript provides are more robust solution that will improve documentation and scalability.

Give me the go ahead and I'll add the setup and convert the existing code into TypeScript.

This should not interfere with those that would still like to create javascript files, in fact it would only improve their developer experience!

**Comment by SauveJeanLuc** [comment]
That's a great idea @gaber85.
Go for it.
