### ISSUE TITLE
Bug: Dropdown options should not be editable

### ISSUE THREAD

**Issue by Dbest2018** [SauveJeanLuc/coffee-tasks#125]
![Screenshot (13)](https://user-images.githubusercontent.com/40031372/195636625-6148d9ff-0b1c-4ed3-b82e-73e8bfa213a4.png)
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] This is bug in the application 🐛
- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository

**Describe the bug** \
The options from the selection menu, can be edited, and also I noticed this was mentioned in the currently merged PR #119  

**To Reproduce** \

**Comment by BismeetSingh** [comment]
Hi, I would like to work on this, can you add the hacktoberfest label and assign it to me.

**Comment by Dbest2018** [comment]
@BismeetSingh hmm, having it as a searchable is odd, but if it is a feature then this issue can be discarded

**Comment by BismeetSingh** [comment]
All bugs are features 😆
