### ISSUE TITLE
Bug: Strange behavior in select

### ISSUE THREAD

**Issue by BrunoLagoa** [SauveJeanLuc/coffee-tasks#126]
Strange behavior in select, showing an input with a blue border. If it makes sense to adjust, you can add this issue in my name to resolve.

<img width="255" alt="Captura de Tela 2022-10-13 às 13 55 46" src="https://user-images.githubusercontent.com/3878945/195658620-95d8c7f4-d5c6-49c6-acd4-304481ecbb29.png">

**Comment by SauveJeanLuc** [comment]
Great, @BrunoLagoa go for it.

**Comment by SauveJeanLuc** [comment]
You can remove The Blue Border on Title Input as well.

**Comment by SauveJeanLuc** [comment]
This should tackle #125 as well.

**Comment by BrunoLagoa** [comment]
ok, i will act on this adjustment.
