### ISSUE TITLE
Adding Date and Time to Tasks

### ISSUE THREAD

**Issue by annupriy** [SauveJeanLuc/coffee-tasks#127]
We can add a date and time for each task. That will engage the user and will keep track of his/her tasks, 
If you found it useful, please assign this to me.

**Comment by SauveJeanLuc** [comment]
Can you give a visual representation of what it will look like?
Don't you think it can ruin the app's simplicity?

**Comment by annupriy** [comment]
You are right! Adding the date and time might make it look a little bit messy. How about adding a timer to every task? That will only take a small space in every taskbar.

**Comment by SauveJeanLuc** [comment]
@annupriy , Like right clicking on task, see option to add timer, set minutes or hours, then a clock icon counting appears on the task.

That would be great. You can raise an issue for that. And If we'll need a design for that we'll raise in issue for it as well.

**Comment by annupriy** [comment]
Sure
