### ISSUE TITLE
Delete a task should have a confirmation dialog

### ISSUE THREAD

**Issue by manassahoo-dev** [SauveJeanLuc/coffee-tasks#134]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] This is bug in the application 🐛
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

**Describe the bug** \
Delete a task should have a confirmation dialog

**To Reproduce** \

1. Click on Delete icon on any of the task
2. Task gets deleted

**Expected behavior** \
Delete Click event should open a confirmation message. Based on that user can delete the task. This will help preventing the mistake to delete a task.

**Current behaviour** \
A clear and consise description of what is happening. If possible, give reasoning behind difference in current behaviour and expected behaviour

**Possible solutions** (Optional) \
Give ideas for solving the problem, provide relevant links to additional packages you are mentioning

**Screenshots**

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser Brave

**Failure Logs**

Please include any relevant log snippets or files here.

**Additional context**

**Comment by manassahoo-dev** [comment]
[Screencast from 15-10-22 12:12:57 PM IST.webm](https://user-images.githubusercontent.com/6974223/195973477-60df78f2-a911-47e1-a8bf-dafbff3bc3a2.webm)

**Comment by SauveJeanLuc** [comment]
You are right,
Go for it @manassahoo-dev

**Comment by manassahoo-dev** [comment]
@SauveJeanLuc I am getting the error while running in my local machine.
![image](https://user-images.githubusercontent.com/6974223/196049340-fdf3446e-86e4-4f35-b8cb-8f6c1956d293.png)

**Comment by uKiJo** [comment]
I added the feature, take a look at the pull request!

**Comment by SauveJeanLuc** [comment]
> @SauveJeanLuc I am getting the error while running in my local machine. ![image](https://user-images.githubusercontent.com/6974223/196049340-fdf3446e-86e4-4f35-b8cb-8f6c1956d293.png)

remove node_modules and redo npm i
