### ISSUE TITLE
Bug layout app not match with figma

### ISSUE THREAD

**Issue by rodrigoodev** [SauveJeanLuc/coffee-tasks#141]
App: 
![image](https://user-images.githubusercontent.com/64027203/196054231-149e88b0-68e8-4daa-a326-c5e08636ac5b.png)

Figma: 
![image](https://user-images.githubusercontent.com/64027203/196054248-363daec8-fa9b-4d38-8446-c38859835dac.png)

The buttons have to stay in space between without padding

**Comment by SauveJeanLuc** [comment]
@rodrigoodev  What do you personally find good between the two as a user and why if u don't mind me asking ?
