### ISSUE TITLE
Add List Tasks by Category Functionality

### ISSUE THREAD

**Issue by SauveJeanLuc** [SauveJeanLuc/coffee-tasks#15]
Users should be able to list tasks by category (All - Complete - Incomplete)

![image](https://user-images.githubusercontent.com/68426990/192339841-83d45646-2c4d-4ada-9ba7-2508c610917b.png)

**Comment by codegoggins** [comment]
Hey !
This is my very first time contributing to open source. How exactly should I contribute to this project ? I am new to Open Source , it would be great if you could help.

**Comment by SauveJeanLuc** [comment]
Glad to hear @codegoggins .
Welcome to the Open-Source Community 🎉

Do you usually code in react ?
And are you familiar with JavaScript ?

**Comment by codegoggins** [comment]
Thanks @SauveJeanLuc 
I am familiar with JavaScript and have done some basic projects in React. But would love to learn new stuff and implement them.

**Comment by SauveJeanLuc** [comment]
Wow, That's exciting @codegoggins.
You can take reference to this [article](https://opensource.guide/how-to-contribute/#opening-a-pull-request)  if you are to make your first contribution then.

If you will, you can start with this task for your very first trial.
And I'll be there to assist wherever needed.

**Comment by codegoggins** [comment]
@SauveJeanLuc Thanks for the task👍 . Will start implementing the feature .

**Comment by SauveJeanLuc** [comment]
Great, I'm assigning it to you then 🙂

**Comment by aadi58002** [comment]
Can i also take part in this?

**Comment by SauveJeanLuc** [comment]
@aadi58002 .
Take it, no worries
