### ISSUE TITLE
Position Placeholder in Add New Task Pop-Up

### ISSUE THREAD

**Issue by SauveJeanLuc** [SauveJeanLuc/coffee-tasks#18]
The two placeholders should be on the same left margin.

![image](https://user-images.githubusercontent.com/68426990/192361221-efa654ba-5043-4402-85bd-fa435a8f89ec.png)

**Comment by Miteshhsingla** [comment]
hey i would like to provide the solution

**Comment by SauveJeanLuc** [comment]
Yup, @Miteshhsingla It's yours.

**Comment by Miteshhsingla** [comment]
I guess if we add box-sizing = border-box; it should be solved.

**Comment by aritroCoder** [comment]
is it too late now to work on this issue?

**Comment by SauveJeanLuc** [comment]
Nop, You can co-author this with @Miteshhsingla .
Glad you are here 🎉

**Comment by aritroCoder** [comment]
Okay, can I create a PR for this issue now or I have to wait until hacktoberfest officially validates the other PR?
