### ISSUE TITLE
Make Add New Task Pop-Up responsive

### ISSUE THREAD

**Issue by SauveJeanLuc** [SauveJeanLuc/coffee-tasks#20]
Currently the "Add New Task Pop-Up" fails on many responsiveness tests.

![image](https://user-images.githubusercontent.com/68426990/192366353-4f18888a-1e36-4a32-b66c-fcbe88659862.png)

![image](https://user-images.githubusercontent.com/68426990/192366475-802172cf-70d7-4bea-8158-369f8e13f943.png)

**Comment by divyanshraj0408** [comment]
Hey this seems interesting! I would like to work on this issue for hacktoberfest.

**Comment by SauveJeanLuc** [comment]
Great @divyanshraj0408 .
It's yours.

**Comment by SandeshGC** [comment]
Hey there! I would like to work on this too for hacktoberfest.

**Comment by SandeshGC** [comment]
Hi, @SauveJeanLuc ! I have worked on this issue without using media queries. I think it would have been easier if we were to create a CSS file for the styles. What do you think of it? Do you want me to use media queries or is it okay?
![smallest sc
![largest screen](https://user-images.githubusercontent.com/59115123/193401336-89b0c1fa-cacf-45b3-a106-f52e176bda5d.png)
reen](https://user-images.githubusercontent.com/59115123/193401329-5fde58de-4069-4935-8417-5b47f2f8cfe7.png)

**Comment by SandeshGC** [comment]
Here is another screenshot for large screens:
![largest screen](https://user-images.githubusercontent.com/59115123/193401347-5fbb41bd-9d63-475f-a991-2e4095913f75.png)

**Comment by SauveJeanLuc** [comment]
> you think of it? D

That's fine.
Raise a PR for this.

**Comment by divyanshraj0408** [comment]
Hey @SauveJeanLuc I think it is better for me to unassign myself from the issue, as @SandeshGC has done a phenomenal job in making the pop up responsive!

**Comment by SauveJeanLuc** [comment]
> PR for this.

No worries
