### ISSUE TITLE
Add Tailwind Set-up to Project

### ISSUE THREAD

**Issue by SauveJeanLuc** [SauveJeanLuc/coffee-tasks#21]
The project is currently relying on vanilla CSS.
Add we want to add some tailwind in the ride, will you help 😺?

**Comment by codegoggins** [comment]
@SauveJeanLuc Hi Again !! I enjoy working with tailwind CSS . It would be great if you allow me to work on this .

**Comment by SauveJeanLuc** [comment]
Cool, It's yours again 🙂 @codegoggins .

**Comment by Onyelaudochukwuka** [comment]
I'll like to work with @codegoggins on this

**Comment by SauveJeanLuc** [comment]
No prob @Onyelaudochukwuka .
Hope you are not raising different PRs on this though.

**Comment by Onyelaudochukwuka** [comment]
I wasn't assigned so no..

**Comment by Onyelaudochukwuka** [comment]
@codegoggins how are we going to go about collaborations?

**Comment by Onyelaudochukwuka** [comment]
Mistakenly took out my assignment, sorry about that

**Comment by messiovo** [comment]
Can I join the team to work on it?

**Comment by Onyelaudochukwuka** [comment]
Ok

**Comment by Onyelaudochukwuka** [comment]
I'll add you as a contributor to my fork

**Comment by Onyelaudochukwuka** [comment]
The link to the repo we'll be working with
https://github.com/Onyelaudochukwuka/coffee-tasks

**Comment by adi-uchiha** [comment]
Working on it, will soon create a PR

**Comment by Onyelaudochukwuka** [comment]
> Working on it, will soon create a PR
> 

We'll be creating a pull request tomorrow as we're nearly done
