### ISSUE TITLE
In Need Of Senior React Devs to Help in Project Maintenance 🙂

### ISSUE THREAD

**Issue by SauveJeanLuc** [SauveJeanLuc/coffee-tasks#22]
Let's have a discussion on this in #14 🙂

**Comment by akhilsharmaa** [comment]
I Would like to be a Maintainer. It would be helpful if we could discuss the project.

**Comment by Onyelaudochukwuka** [comment]
I would love to help out with this 🍻

**Comment by akhilsharmaa** [comment]
@SauveJeanLuc  I think we can fix the meet at 8:30 pm IST Today.
Here is my discord username ID - 750274392097030165.

**Comment by Onyelaudochukwuka** [comment]
Absolutely, that'll be 4pm by my time zone no qualms with that 💪🏽

**Comment by SauveJeanLuc** [comment]
> akhilsharmaa

Great,
@akhilsharmaa and @Onyelaudochukwuka ,
You can join the discord server through the invite: https://discord.gg/ZXBxStbA
And I'll add you to the maintainers channel.

**Comment by Substancia** [comment]
Is it too late for me to tag in?

**Comment by SauveJeanLuc** [comment]
> Is it too late for me to tag in?

Nop, It's nvr too late @Substancia .
You can join the server and ask me to add you to maintainers channel.
We'll schedule a short meeting bfr you are accepted.

**Comment by thisisharsh7** [comment]
@SauveJeanLuc  I'd like to contribute in this project as a hacktober project if there are any spots left
