### ISSUE TITLE
Mobile responsiveness optimizations 

### ISSUE THREAD

**Issue by Onyelaudochukwuka** [SauveJeanLuc/coffee-tasks#23]
Pop up needs some optimizations for mobile devices

![Screenshot_2022-09-26-23-04-28-754_com.android.chrome.jpg](https://user-images.githubusercontent.com/82924100/192389071-96b7f52d-35dd-4e6c-a37d-2854500dece6.jpg)

**Comment by MarcosVel** [comment]
can I do it?

**Comment by SauveJeanLuc** [comment]
Thanks for your concern @Onyelaudochukwuka and @MarcosVel .
But this was already mentioned in #20 .

**Comment by Onyelaudochukwuka** [comment]
Oh didn't notice it
