### ISSUE TITLE
warning: Duplicate key "padding" in object literal

### ISSUE THREAD

**Issue by aritroCoder** [SauveJeanLuc/coffee-tasks#24]
![image](https://user-images.githubusercontent.com/92646038/192613213-c746e2f3-5503-4622-9d39-343a5d224364.png)

When we try to run the project in vite, it shows a warning, which should be resolved

**Comment by SauveJeanLuc** [comment]
That's awesome.
It's yours @aritroCoder

**Comment by aritroCoder** [comment]
Just asking for small clarification, the PR I will make will fix both issue #18 and this issue together, so will there be any difficulty while merging my PR as another person is also working on the issue 18?

**Comment by SauveJeanLuc** [comment]
@aritroCoder I think it doesn't necessarily have to fix #18.
You can still find a way to fix it without working on #18.

You can raise a PR on this and we'll talk about it.
