### ISSUE TITLE
Making Popup buttons clickable 

### ISSUE THREAD

**Issue by saimaheshtaduri** [SauveJeanLuc/coffee-tasks#29]
The Buttons Add Task and Cancel should be responsive on click and hover events, so the end-user can know the button was clicked.

**Comment by SauveJeanLuc** [comment]
> The Buttons Add Task and Cancel should be responsive on click and hover events, so the end-user can know the button was clicked.

![image](https://user-images.githubusercontent.com/68426990/193356068-9d350cfa-05a8-4960-ba13-f6bd0089618e.png)

**Comment by aadi58002** [comment]
Can i take this one ?

**Comment by aadi58002** [comment]
Can i also work on this issue?

**Comment by chamodperera** [comment]
Hi, can I work on this?

**Comment by saimaheshtaduri** [comment]
@SauveJeanLuc  done adding the hover and clicks. 
on clicking cancel, the popup has to close and its the function of another issue, so I left it the same. 

please review and let me know if you need any updates. 
Thanks :)

**Comment by saimaheshtaduri** [comment]
@SauveJeanLuc can you add appropriate labels for this issue ?
