### ISSUE TITLE
Update existing task

### ISSUE THREAD

**Issue by SauveJeanLuc** [SauveJeanLuc/coffee-tasks#3]
There's currently no way to update an existing Task.
**NB:** 
* This should be done by using Local Storage.
* This waits for issue #2

**Comment by suryansh-bhatnagar** [comment]
Hey @SauveJeanLuc  can i work on this issue??

**Comment by adi-uchiha** [comment]
Working on this, will soon create a PR

**Comment by SauveJeanLuc** [comment]
> Working on this, will soon create a PR

Looking forward to receiving it.
