### ISSUE TITLE
Beautify README.md 

### ISSUE THREAD

**Issue by akhilsharmaa** [SauveJeanLuc/coffee-tasks#36]
- Properly Align the texts. 
- Fix Typo. 
- Improve the Image
Show your creativity.

**Comment by divyanshraj0408** [comment]
Hey I would like to work on this issue, can you explain what kind of changes we want in the readme?

**Comment by akhilsharmaa** [comment]
Yes @divyanshraj0408  you are good to go...

**Comment by AyushSarode** [comment]
can you assign me for this project?

**Comment by codeboyfriend** [comment]
Can I work on it??

**Comment by kalyanikakade123** [comment]
Can you assign this issue to me ?
