### ISSUE TITLE
Make an Appealing README for #Hacktoberfest Contestants

### ISSUE THREAD

**Issue by SauveJeanLuc** [SauveJeanLuc/coffee-tasks#4]
The current README.md file seem to need some improvements to make it more appealing.

**Comment by kubahasek** [comment]
@SauveJeanLuc can I grab this please? Assuming I will be commiting on October 1st so it'd apply for hacktoberfest :)

Do you have anything in particular in mind?

**Comment by SauveJeanLuc** [comment]
@kubahasek That would be great.

And This repo has been made with #hacktoberfest in mind.
All PRs are to be merged from the 1st of October.

**Comment by degr8sid-code** [comment]
Can more than one person take over this task? I am also interested.

**Comment by SauveJeanLuc** [comment]
> Can more than one person take over this task? I am also interested.

@degr8sid-code do you have anything else in mind ?
