### ISSUE TITLE
bug: Tasks are not showing up in UI

### ISSUE THREAD

**Issue by adi-uchiha** [SauveJeanLuc/coffee-tasks#42]
The task are getting stored locally but they are not getting listed in the UI

https://user-images.githubusercontent.com/103348863/193470440-73e4bf45-5a3b-4c71-90da-22dd7ebd67ab.mp4

**Comment by adi-uchiha** [comment]
@SauveJeanLuc 
Can you please label this 'hacktoberfest'
I can make a PR on this issue

**Comment by SauveJeanLuc** [comment]
> @SauveJeanLuc Can you please label this 'hacktoberfest' I can make a PR on this issue

done
