### ISSUE TITLE
Pop-Up is way too big for desktop users

### ISSUE THREAD

**Issue by SauveJeanLuc** [SauveJeanLuc/coffee-tasks#45]
The Pop-Up should have a moderate size for desktop users as well as staying responsive for mobile devices.

![image](https://user-images.githubusercontent.com/68426990/193561458-c987e644-8783-49fd-a0bd-6e52d9db128b.png)

**Comment by prateek-1606** [comment]
Hey @SauveJeanLuc . I can solve this issue . Can you assign it to me.
Thanks

**Comment by aleksanderwalczuk** [comment]
@SauveJeanLuc is there any design provided for that?

**Comment by aleksanderwalczuk** [comment]
Ok, I've found it in the readme.
