### ISSUE TITLE
No id field for created task

### ISSUE THREAD

**Issue by aleksanderwalczuk** [SauveJeanLuc/coffee-tasks#48]
- [x] This is bug in the application 🐛
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

**Describe the bug** \
`addTask` functionality provides no `id` field for created task.

**Expected behavior** \

**Current behaviour** \
A clear and consise description of what is happening. If possible, give reasoning behind difference in current behaviour and expected behaviour

**Possible solutions** (Optional) \
Add random id generator like [nanoid](https://www.npmjs.com/package/nanoid) or [uuid](https://www.npmjs.com/package/uuid)

**Comment by Sandyacvedo** [comment]
hey, can i work on this ?

**Comment by aleksanderwalczuk** [comment]
@Sandyacvedo I think we should wait for the maintainer response.

**Comment by SauveJeanLuc** [comment]
Yup, @Sandyacvedo and @aleksanderwalczuk you can go for it.

**Comment by abhishekpatil4** [comment]
@aleksanderwalczuk Assign me this task, I'm a full-stack developer and will get it done in no time

**Comment by aleksanderwalczuk** [comment]
> @aleksanderwalczuk Assign me this task, I'm a full-stack developer and will get it done in no time

You can go for it.
