### ISSUE TITLE
Provide AI suggestions while creating a new Task (Integration with OpenAI APIs)

### ISSUE THREAD

**Issue by SauveJeanLuc** [SauveJeanLuc/coffee-tasks#52]
Users should get task completion suggestions as they type in what they are going to do in the day.

**Comment by aleksanderwalczuk** [comment]
Nice one. I think we should make a toggle/feature flag for that because of rate limits. https://help.openai.com/en/articles/5955598-is-api-usage-subject-to-any-rate-limits
WDYT?

**Comment by SauveJeanLuc** [comment]
> Nice one. I think we should make a toggle/feature flag for that because of rate limits. https://help.openai.com/en/articles/5955598-is-api-usage-subject-to-any-rate-limits WDYT?

Yeah, you've got it right.
But what do u think, if this comes later?
I don't think we are going to have such a number of requests at this stage.

**Comment by aleksanderwalczuk** [comment]
> > Nice one. I think we should make a toggle/feature flag for that because of rate limits. https://help.openai.com/en/articles/5955598-is-api-usage-subject-to-any-rate-limits WDYT?
> 
> Yeah, you've got it right. But what do u think, if this comes later? I don't think we are going to have such a number of requests at this stage.

Good point.

**Comment by SauveJeanLuc** [comment]
@aleksanderwalczuk  Would you mind if I assign this issue to you?

**Comment by SahilAnower** [comment]
Is this open to take?

**Comment by SauveJeanLuc** [comment]
Of course @SahilAnower

**Comment by SahilAnower** [comment]
Hey Just wanted to clear that users should get suggestions just like gmail kind of when we write emails right? The textbox can be a bit larger otherwise it would be hectic for user to see the whole suggestion in one go.

**Comment by SauveJeanLuc** [comment]
@SahilAnower , you can raise a PR for that no Prob. We'll review it as you progress
