### ISSUE TITLE
UX Writing - Task vs Todo

### ISSUE THREAD

**Issue by pobrebobby** [SauveJeanLuc/coffee-tasks#54]
There are 3 instances of the word “task” and 2 instances of the word “todo”.

This can cause confusion to the user. Users like simple and concise action. We don’t want to confuse them.

The word “todo” is really not a widely used word. “To-do” is a more acceptable word. 

<img width="1724" alt="Frame 6" src="https://user-images.githubusercontent.com/115002742/193814481-59d0f85a-6333-4771-8062-3ee5318a554e.png">

**Comment by vaishnavi-nawghare** [comment]
I can work on this issue, will try to give my best in order to make user experience better

**Comment by SauveJeanLuc** [comment]
@vaishnavi-nawghare , yup it's yours.

**Comment by suryansh-bhatnagar** [comment]
@SauveJeanLuc  hey can i work on this??

**Comment by pobrebobby** [comment]
Please take a look at - Pull Request - #82 Updated Figma file if you have any suggestions. Thanks

**Comment by SauveJeanLuc** [comment]
Yp @suryansh-bhatnagar go for it.

**Comment by suryansh-bhatnagar** [comment]
> Yp @suryansh-bhatnagar go for it.

Ok will give PR tonight.
