### ISSUE TITLE
Header part containing Add Task button and Select is not Responsive

### ISSUE THREAD

**Issue by SauveJeanLuc** [SauveJeanLuc/coffee-tasks#61]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] This is bug in the application 🐛
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

**Describe the bug** 
Buttons Add Task and Select in the header are not responsive on smaller screens.

**To Reproduce** \
1. Visit the web-app on a mobile phone
2. View the version of web on smaller devices through inspect

**Expected behavior** \
The two buttons Add Task and Select should maintain the space between them on smaller screens evenly, and have the size short.

**Current behaviour** \
The two buttons Add Task and Select doesn't maintain the space between them on smaller screens.

**Screenshots**
![Screenshot_20221006-120954](https://user-images.githubusercontent.com/68426990/194288876-93f9f1c5-ad6c-413c-b70c-a1e2d2bbf277.png)

**Smartphone (please complete the following information):**
 - Device: Techno Pop 2F
 - OS: Android
 - Browser: Chrome

**Comment by SauveJeanLuc** [comment]
@Olumarshal Yes, It's yours.

**Comment by SauveJeanLuc** [comment]
@adnansam110, would you mind taking #66 ?

**Comment by Prakhar-Goyal-3014** [comment]
#67 Please check my pull request the issue is solved

**Comment by adnansam110** [comment]
@SauveJeanLuc Yeah Sure
