### ISSUE TITLE
Replace JavaScript Alert Box with in place alert Message

### ISSUE THREAD

**Issue by manassahoo-dev** [SauveJeanLuc/coffee-tasks#68]
![image](https://user-images.githubusercontent.com/6974223/194319889-c4243642-a210-4669-a298-2bc1029f46a9.png)

**Comment by bloodmonk7** [comment]
Can I do this?

**Comment by 2brownc** [comment]
I am interested to work on this. Can I be assigned this?

**Comment by SauveJeanLuc** [comment]
@2brownc , A PR was already raised for this.
Hwvr, stay tuned, they are many more other issues under way
