### ISSUE TITLE
Complete or incomplete tasks are not differentiable in list

### ISSUE THREAD

**Issue by ayush4345** [SauveJeanLuc/coffee-tasks#70]
![Screenshot_2022-10-06-20-25-06-533_com.android.chrome.jpg](https://user-images.githubusercontent.com/99096397/194346704-83e46727-2b9a-41c3-ba1a-742cdb0f020a.jpg)

When we add task and whether we choose complete or incomplete in both case it task added look exactly same.

There should be difference between completed or incomplete tasks when we add them.

##  solution

1.I think either we should write completed or incompleted in row same as task on right side.or,

2.Designate some symbol for completed or incompleted.

I want to work on this.

What is your opinion, regarding this..?

**Comment by SauveJeanLuc** [comment]
@ayush4345 , @IRSHIT033 , we are waiting for #19 to be able to work on this.
All current implementations are only for test purpose.
