### ISSUE TITLE
Add Prettier into Project

### ISSUE THREAD

**Issue by RichardHpa** [SauveJeanLuc/coffee-tasks#86]
With so many people working on this project it would be good to add some automated formatting to make sure that all the code is formatted properly.

Currently alot of the merge conflicts are to do with formatting and this comes from each person using their own editors all with different settings.

Adding in prettier with and some rules for the repo will help with these merge conflicts and with the overall quantity of the code.

We already have Husky installed to help with linting so it would also be good to include prettier auto formatting into that too so that whenever someone makes a commit it auto formats to the repos settings.

**Comment by SauveJeanLuc** [comment]
Great idea @RichardHpa

**Comment by RichardHpa** [comment]
@SauveJeanLuc Just put up a PR for this. It kind of needs to be merged in next as it would cause all exisiting PR's to fail.

**Comment by RichardHpa** [comment]
Closed with #98
