### ISSUE TITLE
Add a "Remove" icon to remove added tasks

### ISSUE THREAD

**Issue by SandeshGC** [SauveJeanLuc/coffee-tasks#87]
A "remove" feature is needed to remove the tasks from the list after adding. I suggest we use a remove icon svg at the right side of the task after the 'task-status' label.

- [x] This is bug in the application 🐛
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

After this change, user will be able to remove task from the list by clicking the "remove icon"

**Comment by Rinshin-Jalal** [comment]
There is no way to delete or edit or archive the todos

**Comment by SandeshGC** [comment]
I can work on deleting the tasks. Assign it to me!

**Comment by Rinshin-Jalal** [comment]
I'm not a maintainer

but this is already in development 

#19

**Comment by SandeshGC** [comment]
The issue #19  is for Figma design, I am talking about adding actual functionalities to the page.

**Comment by SauveJeanLuc** [comment]
@SandeshGC #85, is only for listing.
You can do them both either way, if you will.

**Comment by SandeshGC** [comment]
I was thinking of adding only the remove button for now as this issue is only about being able to remove the added tasks.

Ok then, I would like to add the icons with their functionalities. Let's wait for the reply on #85 and then you can assign it to me @SauveJeanLuc
